#!/bin/bash
# Author: zhouzp
# Created Time : Tue 17 Jul 2020 10:35:49 PM CST
# File Name: loop
# Description:

function loop_exe()
{
    alias gitpush="git push origin master"
    local ex_count=0
    while true ; do
        #command
        sleep 1
        echo The command is \"$*\"
        echo
        $*
        if [ $? == 0 ] ; then
            echo
            echo The command execute OK!
            break;
        else
            (( ex_count = ${ex_count} + 1 ))
            echo ERROR : The command execute fialed! ex_count = ${ex_count}.
        fi
    done
}

loop_exe $*
